package water.util;

/**
 * Functions of N parameters
 * generated by this script:
    def p(ss: Seq[String]) = ss grouped 10 map (_ mkString ",") mkString ",\n      "
    def g(n:Int) { println(
      s"""
 public interface Function$n<${p((1 to n) map ("X"+_))}, Y> {
   Y apply(${p((1 to n) map (i => s"X$i x$i"))});
 }""".tail)
   }
   def gen(n:Int) = 1 to n foreach g
 */
public final class Functions {
  public interface Function1<X1, Y> {
    Y apply(X1 x1);
  }
  public interface Function2<X1,X2, Y> {
    Y apply(X1 x1,X2 x2);
  }
  public interface Function3<X1,X2,X3, Y> {
    Y apply(X1 x1,X2 x2,X3 x3);
  }
  public interface Function4<X1,X2,X3,X4, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4);
  }
  public interface Function5<X1,X2,X3,X4,X5, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5);
  }
  public interface Function6<X1,X2,X3,X4,X5,X6, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6);
  }
  public interface Function7<X1,X2,X3,X4,X5,X6,X7, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7);
  }
  public interface Function8<X1,X2,X3,X4,X5,X6,X7,X8, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8);
  }
  public interface Function9<X1,X2,X3,X4,X5,X6,X7,X8,X9, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9);
  }
  public interface Function10<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10);
  }
  public interface Function11<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11);
  }
  public interface Function12<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12);
  }
  public interface Function13<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13);
  }
  public interface Function14<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14);
  }
  public interface Function15<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15);
  }
  public interface Function16<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16);
  }
  public interface Function17<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17);
  }
  public interface Function18<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18);
  }
  public interface Function19<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19);
  }
  public interface Function20<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20);
  }
  public interface Function21<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21);
  }
  public interface Function22<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22);
  }
  public interface Function23<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23);
  }
  public interface Function24<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24);
  }
  public interface Function25<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25);
  }
  public interface Function26<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26);
  }
  public interface Function27<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27);
  }
  public interface Function28<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28);
  }
  public interface Function29<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29);
  }
  public interface Function30<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30);
  }
  public interface Function31<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31);
  }
  public interface Function32<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32);
  }
  public interface Function33<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33);
  }
  public interface Function34<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34);
  }
  public interface Function35<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35);
  }
  public interface Function36<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36);
  }
  public interface Function37<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37);
  }
  public interface Function38<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37,X38, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37,X38 x38);
  }
  public interface Function39<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37,X38,X39, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37,X38 x38,X39 x39);
  }
  public interface Function40<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37,X38,X39,X40, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37,X38 x38,X39 x39,X40 x40);
  }
  public interface Function41<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37,X38,X39,X40,
      X41, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37,X38 x38,X39 x39,X40 x40,
            X41 x41);
  }
  public interface Function42<X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,
      X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,
      X21,X22,X23,X24,X25,X26,X27,X28,X29,X30,
      X31,X32,X33,X34,X35,X36,X37,X38,X39,X40,
      X41,X42, Y> {
    Y apply(X1 x1,X2 x2,X3 x3,X4 x4,X5 x5,X6 x6,X7 x7,X8 x8,X9 x9,X10 x10,
            X11 x11,X12 x12,X13 x13,X14 x14,X15 x15,X16 x16,X17 x17,X18 x18,X19 x19,X20 x20,
            X21 x21,X22 x22,X23 x23,X24 x24,X25 x25,X26 x26,X27 x27,X28 x28,X29 x29,X30 x30,
            X31 x31,X32 x32,X33 x33,X34 x34,X35 x35,X36 x36,X37 x37,X38 x38,X39 x39,X40 x40,
            X41 x41,X42 x42);
  }
}

